### ISSUE TITLE
A archiver?

### ISSUE THREAD

**Issue by bzg** [etalab/biryani#11]
Ce dépôt de code source ne semble plus actif, le lien vers https://biryani.readthedocs.io est cassé.

Est-ce qu'il faudrait l'archiver?

**Comment by bzg** [comment]
cc @maukoquiroga

**Comment by bonjourmauko** [comment]
Hello @bzg ! Cette librairie est effectivement en train d'être dépréciée.

Or il me semble que la migration n'a pas été encore faite par tout le monde. 

Je propose de la transférer à l'organisation OpenFisca.

**Comment by bzg** [comment]
Merci pour ta réponse !

> Je propose de la transférer à l'organisation OpenFisca.

LGTM.
